name: Plugin compatibility
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11.x.x
      - name: Build the plugin using Gradle
        run: ./gradlew buildPlugin
      - uses: thepieterdc/intellij-plugin-verifier-action@1.3.0
        with:
          plugin: '/home/runner/work/clean-spring/clean-spring/build/distributions/clean-spring-*'
          versions: |
            2020.3.4
            2021.1.3
